[[plugins]] # TOMLのシンタックスハイライト
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'scrooloose/syntastic'
hook_source = '''
  let g:syntastic_mode_map = {'mode': 'passive', 'active_filetypes': ['python', 'ruby']}
  let g:syntastic_python_checkers = ['pyflakes', 'pep8']
  let g:syntastic_ruby_checkers = ['rubocop']
  let g:syntastic_check_on_open = 1
'''

# Rust
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']
hook_source = '''
let g:rustfmt_autosave = 1
let g:rustfmt_command = '$HOME/.cargo/bin/rustfmt'
'''

[[plugins]]
repo = 'sebastianmarkow/deoplete-rust'
on_ft = 'rust'
depends = ['deoplete.nvim']
hook_source = '''
    let g:deoplete#sources#rust#racer_binary="$HOME/.cargo/bin/racer"
    let g:deoplete#sources#rust#rust_source_path='$HOME/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/'
    let g:deoplete#sources#rust#show_duplicates=1
    let g:deoplete#sources#rust#disable_keymap=1
    nmap <buffer> gd <plug>DeopleteRustGoToDefinitionDefault
    nmap <buffer> K  <plug>DeopleteRustShowDocumentation
'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = '''
    let g:go_fmt_command = "goimports"
    let g:go_def_mapping_enabled = 0
    let g:go_doc_keywordprg_enabled = 0
'''

[[plugins]]
repo = 'deoplete-plugins/deoplete-jedi'
on_ft = 'py'
hook_add = '''
    let g:python3_host_prog = '/full/path/to/neovim3/bin/python'
'''

[[plugins]]
repo = 'deoplete-plugins/deoplete-go'
on_ft = 'go'
hook_add = '''
    let g:deoplete#sources#go#gocode_binary = $GOPATH.'/bin/gocode'
    let g:deoplete#sources#go#sort_class = ['package', 'func', 'type', 'var', 'const']
'''

[[plugins]]
repo = 'IN3D/vim-raml'

[[plugins]]
repo = "let-def/vimbufsync"
on_ft = "coq"

[[plugins]]
repo = "the-lambda-church/coquille"
on_ft = "coq"
depends = ["vimbufsync"]
hook_source = """
"""
# MarkDown
[[plugins]]
repo='plasticboy/vim-markdown'
on_ft=['markdown','mkd']
hook_add='''
    let g:vim_markdown_folding_disabled = 1
    let g:vim_markdown_auto_insert_bullets = 0
    let g:vim_markdown_new_list_item_indent = 0
'''

[[plugins]]
on_ft=['markdown','mkd']
repo = 'godlygeek/tabular'

[[plugins]]
on_ft=['markdown','mkd', 'md']
repo = 'kannokanno/previm'
