[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # color scheme
repo = 'w0ng/vim-hybrid'
hook_add = '''
set background=dark
colorscheme hybrid
'''

[[plugins]] # search files
repo   = 'Shougo/unite.vim'
hook_add = '''
let g:unite_enable_start_insert=1
let g:unite_source_history_yank_enable =1
let g:unite_source_file_mru_limit = 200
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
let NERDTreeShowHidden = 1
nnoremap <silent><C-e> :NERDTreeToggle<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo   = 'Shougo/neomru.vim'

[[plugins]] # completion
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1
hook_add = '''
let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ], [ 'readonly', 'absolutepath', 'modified' ] ],
      \ }
      \ }
'''

# MarkDown
[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'plasticboy/vim-markdown'
hook_add = '''
    let g:vim_markdown_folding_disabled = 1
    let g:vim_markdown_auto_insert_bullets = 0
    let g:vim_markdown_new_list_item_indent = 0
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# Indent
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_source = '''
    let g:indent_guides_guide_size = 1
    let g:indent_guides_enable_on_vim_startup = 1
    let g:indent_guides_exclude_filetypes = ['help', 'nerdtree']
'''

## Git gutter
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_source = '''
    nmap <Leader>h] <Plug>GitGutterNextHunk
    nmap <Leader>h[ <Plug>GitGutterPrevHunk
    set updatetime=250
'''

## Git fugitive
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo='easymotion/vim-easymotion'
hook_add='''
let g:EasyMotion_do_mapping = 0
let g:EasyMotion_smartcase = 1
map s <Plug>(easymotion-overwin-f)
map s <Plug>(easymotion-overwin-f2)
map <Leader>j <Plug>(easymotion-j)
map <Leader>k <Plug>(easymotion-k)
'''

[[plugins]]
repo='prabirshrestha/vim-lsp'
merged='0'
hook_add='''
let g:lsp_diagnostics_enabled = 1
let g:lsp_signs_enabled = 1
let g:lsp_diagnostics_echo_cursor = 1
let g:lsp_highlights_enabled = 0
let g:lsp_preview_float = 1
let g:lsp_text_edit_enabled = 0
let g:lsp_async_completion = 1
let g:lsp_diagnostics_float_cursor = 1
nnoremap gd :<C-u>LspDefinition<CR>
nnoremap gr :<C-u>LspReferences<CR>
nnoremap gi :<C-u>LspImplementation<CR>
nnoremap gt :<C-u>LspTypeDefinition<CR>
nnoremap <leader>rn :<C-u>LspRename<CR>
nnoremap [g :<C-u>LspPreviousDiagnostic<CR>
nnoremap ]g :<C-u>LspNextDiagnostic<CR>
nnoremap K :<C-u>LspHover<CR>
"python
if executable('pyls')
    " pip install python-language-server
    au User lsp_setup call lsp#register_server({
        \ 'name': 'pyls',
        \ 'cmd': {server_info->['pyls']},
        \ 'allowlist': ['python'],
        \ })
endif
'''

[[plugins]]
repo='mattn/vim-goimports'
hook_add='''
let g:goimports = 1
let g:goimports_simplify = 1
'''
merged='0'

[[plugins]]
repo='mattn/vim-lsp-settings'
merged='0'

[[plugins]]
repo='lighttiger2505/deoplete-vim-lsp'

[[plugins]]
repo='leafgarland/typescript-vim'
